# Generated by Django 2.0.7 on 2018-07-20 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20180710_1101'),
        ('journal', '0002_auto_20180710_1434'),
    ]

    operations = [
    ]
